name: Lib tests

on: [push, pull_request]

jobs:

  style:

    runs-on: ${{ matrix.os }}

    strategy:

      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10"]

    steps:
      - name: Set up Git
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install -r requirements.txt
          python -m pip list

      - name: Run tests
        run: |
          python ./scripts/run_tests.py
